set(_CATKIN_CURRENT_PACKAGE "my_gazebo_launch")
set(my_gazebo_launch_VERSION "0.0.0")
set(my_gazebo_launch_MAINTAINER "root <root@todo.todo>")
set(my_gazebo_launch_PACKAGE_FORMAT "2")
set(my_gazebo_launch_BUILD_DEPENDS "gazebo_ros" "roscpp" "rospy")
set(my_gazebo_launch_BUILD_EXPORT_DEPENDS "gazebo_ros" "roscpp" "rospy")
set(my_gazebo_launch_BUILDTOOL_DEPENDS "catkin")
set(my_gazebo_launch_BUILDTOOL_EXPORT_DEPENDS )
set(my_gazebo_launch_EXEC_DEPENDS "gazebo_ros" "roscpp" "rospy")
set(my_gazebo_launch_RUN_DEPENDS "gazebo_ros" "roscpp" "rospy")
set(my_gazebo_launch_TEST_DEPENDS )
set(my_gazebo_launch_DOC_DEPENDS )
set(my_gazebo_launch_URL_WEBSITE "")
set(my_gazebo_launch_URL_BUGTRACKER "")
set(my_gazebo_launch_URL_REPOSITORY "")
set(my_gazebo_launch_DEPRECATED "")